from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('index.urls')),
    url(r'^index/', include('index.urls', namespace='index')),
    url(r'^ad-effect/', include('ad-effect.urls', namespace='ad-effect')),
    url(r'^ad-schedule/', include('ad-schedule.urls', namespace='ad-schedule')),
    url(r'^cy-guest/', include('cy-guest.urls', namespace='cy-guest')),
    url(r'^cy-list/', include('cy-list.urls', namespace='cy-list')),
    url(r'^cy-outbound/', include('cy-outbound.urls', namespace='cy-outbound')),
    url(r'^cy-result/', include('cy-result.urls', namespace='cy-result')),
    url(r'^cy-test/', include('cy-test.urls', namespace='cy-test')),
    url(r'^db-edit/', include('db-edit.urls', namespace='db-edit')),
    url(r'^db-guest/', include('db-guest.urls', namespace='db-guest')),
    url(r'^db-list/', include('db-list.urls', namespace='db-list')),
    url(r'^db-result/', include('db-result.urls', namespace='db-result')),
    url(r'^info-online/', include('info-online.urls', namespace='info-online')),
    url(r'^ky-input/', include('ky-input.urls', namespace='ky-input')),
    url(r'^ky-remain/', include('ky-remain.urls', namespace='ky-remain')),
    url(r'^ky-result/', include('ky-result.urls', namespace='ky-result')),
    url(r'^locked/', include('locked.urls', namespace='locked')),
    url(r'^login/', include('login.urls', namespace='login')),
    url(r'^page404/', include('page404.urls', namespace='page404')),
    url(r'^page500/', include('page500.urls', namespace='page500')),
    url(r'^page-offline/', include('page-offline.urls', namespace='page-offline')),
    url(r'^setting/', include('setting.urls', namespace='setting')),
    url(r'^signup/', include('signup.urls', namespace='signup')),
    url(r'^tm-input/', include('tm-input.urls', namespace='tm-input')),
    url(r'^tm-public/', include('tm-public.urls', namespace='tm-public')),
    url(r'^tm-result/', include('tm-result.urls', namespace='tm-result')),
    url(r'^forgotpass/', include('forgotpass.urls', namespace='forgotpass')),
]
